apiVersion: v1
kind: Secret
metadata:
  name: online-store-secrets
type: Opaque
stringData:
  Auth__JwtSigningKey: ""
  Stripe__SecretKey: ""
  ConnectionStrings__Catalog: ""
  ConnectionStrings__Users: ""
