apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: patch-ingress.yaml
  - path: patch-serviceaccount.yaml

images:
  - name: ghcr.io/your-org/online-store-gateway
    newName: <gcp_region>-docker.pkg.dev/<gcp_project>/<artifact_repo>/online-store-gateway
    newTag: "1.0.0"
  - name: ghcr.io/your-org/online-store-order-service
    newName: <gcp_region>-docker.pkg.dev/<gcp_project>/<artifact_repo>/online-store-order-service
    newTag: "1.0.0"
  - name: ghcr.io/your-org/online-store-payment-service
    newName: <gcp_region>-docker.pkg.dev/<gcp_project>/<artifact_repo>/online-store-payment-service
    newTag: "1.0.0"
  - name: ghcr.io/your-org/online-store-product-service
    newName: <gcp_region>-docker.pkg.dev/<gcp_project>/<artifact_repo>/online-store-product-service
    newTag: "1.0.0"
  - name: ghcr.io/your-org/online-store-cart-service
    newName: <gcp_region>-docker.pkg.dev/<gcp_project>/<artifact_repo>/online-store-cart-service
    newTag: "1.0.0"
  - name: ghcr.io/your-org/online-store-user-service
    newName: <gcp_region>-docker.pkg.dev/<gcp_project>/<artifact_repo>/online-store-user-service
    newTag: "1.0.0"
  - name: ghcr.io/your-org/online-store-inventory-service
    newName: <gcp_region>-docker.pkg.dev/<gcp_project>/<artifact_repo>/online-store-inventory-service
    newTag: "1.0.0"
  - name: ghcr.io/your-org/online-store-shipping-service
    newName: <gcp_region>-docker.pkg.dev/<gcp_project>/<artifact_repo>/online-store-shipping-service
    newTag: "1.0.0"
  - name: ghcr.io/your-org/online-store-history-service
    newName: <gcp_region>-docker.pkg.dev/<gcp_project>/<artifact_repo>/online-store-history-service
    newTag: "1.0.0"
